name: CI

on:
  push:
    branches: ["main", "master", "develop", "feature/**"]
  pull_request:

jobs:
  build-and-test:
    name: Setup & Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies if package.json exists
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "package.json not found; skipping install"
          fi

      - name: Run lint if configured
        run: |
          if [ -f package.json ] && npm run | grep -q "lint"; then
            npm run lint
          else
            echo "Lint script not configured; skipping"
          fi

      - name: Run tests if configured
        run: |
          if [ -f package.json ] && npm run | grep -q "test"; then
            npm test
          else
            echo "Test script not configured; skipping"
          fi
